### PR TITLE
Create Enrollment and Demographic charts

### PR DESCRIPTION
**Pull request by kmagida110**
## Background
This ticket represents the work of creating the first wave of enrollment and demographic charts in Superset as defined by the tickets below. The resulting charts are in Superset here: http://ec2-3-134-85-99.us-east-2.compute.amazonaws.com/superset/dashboard/3/ and should be reviewed as well. The custom SQL powering the charts is included in this PR and will be updated as new metrics are created.

## GitHub Issue
https://github.com/ctoec/data-collection/issues/1068
https://github.com/ctoec/data-collection/issues/1069

## Validation Plan
Charts created with these metrics should be reviewed by the reviewer and the design team will also check them for both data clarity and design features.

### CODE REVIEW

**Review by JordanGuinn — APPROVED** [review]
SQL here seems fine overall - really most curious about how we go from SQL queries to Superset charts, and what that process looks like (and whether it's manual or automated)?

**Review by bamader — APPROVED** [review]
Dashboards and summary demographics look fine to me. They're a good start to this process. I think there are some subjective presentation things I'd change, but those are probably best reserved for a later meeting. @kmagida110 I wonder if you and I should set up some sort of cadence with Phoebe to clarify questions/interpretations, improve our presentation, etc. (plus we might work out together what good next steps are)

**Comment by bamader** [comment]
Oh lol it looks like my review doesn't count towards mergeability because I don't have write access

**Comment by JordanGuinn** [comment]
@bamader You should have write access now

**Comment by kmagida110** [comment]
@JordanGuinn @bamader Very good questions, on how these actually get converted charts I'll do a little demo at some point tomorrow or the next day. On the approval process, I was thinking we can meet tomorrow once there is a critical mass of charts and metrics and talk through designs and metrics and actually move things and restyle the real things. I'll send something around.

**Pull request merged**
